### ISSUE TITLE
Implement tracking of ultra wideband devices

### ISSUE THREAD

**Issue by selko** [xeokit/xeokit-bim-viewer#116]
Hi all,

Is it possible or someone has some experience in provide tracking of objects inside a bim model uising xeokit-bim-viewer?

I am interested in implement this function to see my actives online.

If someone can help me or suggest another option i would appreciate it. 
thank you very much

**Comment by xeolabs** [comment]
Hi, I'm not familiar with tracking object inside a BIM model - could you please describe this use case in more detail?

**Comment by selko** [comment]
I want to track the movement of a person or a vehicle inside the bim model. This person or vehicle have an uwb device that sends position and coordinates via json for example. The purpose is monitoring in realtime and would be nice to see with 3d bim model.

**Comment by xeolabs** [comment]
Yes, xeokit has the features within it's API to support this use case - see API docs and examples for more info: https://www.notion.so/xeokit/xeokit-Documentation-4598591fcedb4889bf8896750651f74e
