### ISSUE TITLE
Transparent backgroundColor

### ISSUE THREAD

**Issue by ptorrent** [xeokit/xeokit-bim-viewer#120]
Hello there !

Is it possible to make backgroundColor transparent ? setConfigs({ backgroundColor : [0,0,0,0]}) ?

Thanks for your help !

**Comment by baoxiaozhi** [comment]
hey @ptorrent 
The following URL may help you!
 [https://github.com/xeokit/xeokit-bim-viewer#viewer-configurations](url)

**Comment by ptorrent** [comment]
not sure to see transparent property for background ?

**Comment by anoxia3074** [comment]
此问题是如何解决的呢

**Comment by anoxia3074** [comment]
Excuse me, how to set the transparent background color at last?
