### ISSUE TITLE
How to add a new XKT file to the Model Database?

### ISSUE THREAD

**Issue by baoxiaozhi** [xeokit/xeokit-bim-viewer#124]
I have a new .XKT model and I want  to add it to model database to make this model loaded and displayed on viewer correctly. The following is my error report:

[xeokit plugin XKTLoader]: Unsupported .XKT file version: 1329865020 - this XKTLoaderPlugin supports versions 1,2,3,4,5,6,7,8,9,10

but I'm sure that the new .XKT model 's vesion is v10. Is this a model version problem or something else?

**Comment by xeolabs** [comment]
Could you please post some details on how you converted and loaded the XKT?
ie. 

- the commands used, 
- versions of tools
- JS used to view the XKT
- and the XKT file itself.

**Comment by baoxiaozhi** [comment]
hey @xeolabs 
Thanks for your reply. I have solved my problems. This problem is caused by file path and file name. 

Cheers, Bao
