### ISSUE TITLE
Marquee selection tool

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-bim-viewer#132]
Coming up: a 2D marquee selection tool.

* When the user switches from the single select (arrow) tool to the marquee selection tool, the mouse left-click model rotation command should be deactivated and a square would be possible to create with a single click. Rotation could be in this mode switched to for example scroll+SHIFT control for navigation through the model. This is a common arrangement in BIM software.
* A single click in the empty area should deselect all elements.
* New marquee selection, should deselect previously selected elements, except when user is holding CTRL while selecting then it is added selection.
* By creating a marquee selection from left to right, the user selects only elements with boundaries that are completely within the marquee, which is shown with a dashed border.
* By creating a marquee selection from right to left, the user selects elements with boundaries that intersect the marquee, which is shown with a solid border.
* Boundaries are axis-aligned (AABB), which means that they can be fairly loose when they belong to long and thin objects.

[Screencast from 27.04.2023 01:10:59.webm](https://user-images.githubusercontent.com/83100/234721848-da88be8f-eb89-445e-9f49-9be89a92bfa1.webm)

**Comment by Amoki** [comment]
This is a nice feature!
If I see correctly, only objects 100% in the square are selected. An option no be able to select an object half in the square could be useful too. But I understand it may be way more complex to implement
