### ISSUE TITLE
CANNOT rotate my IFC objects

### ISSUE THREAD

**Issue by cactm08062** [xeokit/xeokit-bim-viewer#145]
var CT722 = viewer.scene.objects["3iqvSx__L7LuwWnzJeW$0t"];
    

viewer.scene.on("tick" , function(){
    
    viewer.scene.setObjectsHighlighted(["3iqvSx__L7LuwWnzJeW$0t"], true);
    
    CT722.rotateY(0.3);
});

It shows : Uncaught TypeError: CT722.rotateY is not a function

**Comment by xeolabs** [comment]
This feature is not currently supported. As you have discovered, the `Entity` class has no `rotateY` method.
