### ISSUE TITLE
How can I load ifc file content without src url

### ISSUE THREAD

**Issue by pooja-chokhani** [xeokit/xeokit-bim-viewer#149]
I want to upload a ifc file content from a string. I have all the IFC file content in a string and i want the viewer to load all data from that string. Can you please help me to know if this is possible or not? If yes, then please let me know how can i do that?

**Comment by pooja-chokhani** [comment]
Hello, is there any update on this query?

**Comment by xeolabs** [comment]
No, the API does not currently support this use case. If you can implement this however, along with an example, we can review and merge a PR. Unfortunately we're unable to advise on how to implement this. Will close this issue now, and reopen in case of a contribution.

**Comment by pooja-chokhani** [comment]
Thanks a lot for your support. We will check if we can implement it and we will definitely let you know if  do so.
