### ISSUE TITLE
Minimalst HTML Example possible doesnt work

### ISSUE THREAD

**Issue by seb-esser** [xeokit/xeokit-bim-viewer#165]
Hi there, 
I am a researcher at the Technical University of Munich and am investigating different frameworks to visualize IFC models on the web. Given the circumstances and the stage we have already taught our students this semester in a new course on web technologies for the built environment, we are looking for a framework that lets us show a BIM model with a few code lines (i.e., without bundlers, manual touching of wasm, ... if possible). 

For this, I became aware of your framework. Even though I managed to get the OBJ loader working, I am still failing to run the IFC loader. 

## My setup

I am using a very pure system setup consisting of an HTML file and an express server handing out resources (no bundler, nothing else). 

Here is my HTML file: 

```
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Viewer example</title>
    <style>
        body {
            margin: 0;
            width: 100%;
            height: 100%;
            user-select: none;
        }

        #myCanvas {
            width: 100%;
            height: 100%;
            position: absolute;
            background: lightblue;
            background-image: linear-gradient(lightblue, white);
        }
    </style>
</head>

<body>
    <canvas id="myCanvas"></canvas>
</body>
<script id="source" type="module">

    import {
        Viewer, WebIFCLoaderPlugin, Mesh, loadOBJGeometry, ReadableGeometry,
        MetallicMaterial, Texture
    } from
        "https://cdn.jsdelivr.net/npm/@xeokit/xeokit-sdk/dist/xeokit-sdk.es.min.js";

    const viewer = new Viewer({
        canvasId: "myCanvas",
        transparent: true
    });

    viewer.camera.eye = [-3.933, 2.855, 27.018];
    viewer.camera.look = [4.400, 3.724, 8.899];
    viewer.camera.up = [-0.018, 0.999, 0.039];

    // IFC loader
    const webIFCLoader = new WebIFCLoaderPlugin(viewer, {
        wasmPath: "https://cdn.jsdelivr.net/npm/@xeokit/xeokit-sdk/dist/"
    });

    const model = webIFCLoader.load({
        src: "/Duplex_A",
        edges: true
    }); 

    // OBJ loader
    // loadOBJGeometry(viewer.scene, {
    //     src: "objGeometry",
    //     compressGeometry: false
    // }).then(function (geometryCfg) {
    //     // Success
    //     new Mesh(viewer.scene, {
    //         geometry: new ReadableGeometry(viewer.scene, geometryCfg),
    //         material: new MetallicMaterial(viewer.scene, {
    //             baseColor: [1, 1, 1],
    //             metallic: 1.0,
    //             roughness: 1.0,            
    //             specularF0: 0.7
    //         })
    //     });
    // }, function () {
    //     // Error
    // });

</script>

</html>
```

The respective IFC and OBJ files are served as static resources from an Express server handing out the HTML (to escape any CORS issues): 

```
let express = require("express")
let path = require("path")

var app = express();

app.get("/", (req, res) => {
    res.sendFile(path.join(__dirname, "index.html"))
});

app.get("/Duplex_A", (req, res) => {
    res.sendFile(path.join(__dirname, "Duplex_A.ifc"));
});

app.get("/objGeometry", (req, res) => {
    res.sendFile(path.join(__dirname, "magnolia.obj"));
});

app.listen(3000, () => { console.log("listening to 3000") })
```

## My problem

Even though the visualization of the OBJ file works perfectly fine, I am still running into two error messages when loading the IFC file (see screenshot below). 
The geometry is shown but the loading wheel does not disappear and interaction with the 3D scene is impossible. 

Is there anybody out there who could give me a pointer that I haven't considered so far to solve the problem? 

Any help is highly appreciated!

![grafik](https://github.com/xeokit/xeokit-bim-viewer/assets/56266373/86189d21-a92f-4333-8b20-c265a46df467)

**Comment by xeolabs** [comment]
That's a strange one - I'll check this over the next day or so. That `flagsBuf` should never be null. Is the Duplex_a model the same one as in the examples?

A possible workaround for now could be to switch the Viewer over to it's "data texture" scene representation, in case a different code path within the renderer bypasses this issue until I can debug. This will switch the Viewer from using VBOs to using data textures. Perhaps the bug only happens in VBOs, let's see. Try adding the `dtxEnabled` config to `Viewer` and `WebIFCLoaderPlign.load()`, as shown here:

````javascript
 const viewer = new Viewer({
        canvasId: "myCanvas",
        transparent: true,
        dtxEnabled: true // <<<<---------------- Add this
    });

 //...

  const sceneModel = ifcLoader.load({
      id: "myModel",
      src: "../../assets/models/ifc/Duplex.ifc",
      dtxEnabled: true // <<<<---------------- Add this
  });
````

**Comment by seb-esser** [comment]
Thanks for your quick answer! Unfortunately, your proposal throws another arrow as shown below: 

![grafik](https://github.com/xeokit/xeokit-bim-viewer/assets/56266373/b509d629-fce1-4c20-a80f-af74f09bda8e)

The duplex model should be the same file as you are using in your examples.

**Comment by xeolabs** [comment]
I've never see this error before, I'm a bit stumped. Could you try some earlier versions of xeokit? Perhaps 2.3, 2.2. 

Also, maybe try cloning the repository and running `http-server` locally in the root directory.

This way we can rule out anything Express-related (though I can't think what that would be).

**Comment by seb-esser** [comment]
Apparently, my copy of the Duplex model has some sort of issue. With a new model created in Revit, everything works fine now. 

Thank you for your support!
