### ISSUE TITLE
Question on TreeViewPlugin usage

### ISSUE THREAD

**Issue by knevagi** [xeokit/xeokit-bim-viewer#36]
I am trying to use the xeokit-bim-viewer to display my own IFC model. I converted the IFC model to xkt using ifcconvert,https://github.com/KhronosGroup/COLLADA2GLTF/releases and https://github.com/xeokit/xeokit-gltf-to-xkt. However, when I tried to use the converted model in the viewer it gave me this error.
`[xeokit plugin TreeViewPlugin]: Failed to build storeys hierarchy for model 'architectural' - perhaps this model is not an IFC model?`

Here are the files I used
https://github.com/knevagi/xeokit-test
Any help would be appreciated. Thank you.

**Comment by wielinde** [comment]
Hi @knevagi, I just imported your IFC in OpenProject and the conversion worked fine and I could see the four walls in XEOKIT. So there is something wrong with your IFC to xkt and JSON setup. This is our up-to-date script + instructions for installing the conversion tools on a linux Ubuntu. Please, check the commets at the bottom of the file. https://github.com/opf/openproject/blob/dev/modules/bim/bin/setup_dev.sh

**Comment by jerto** [comment]
Hi, I have exactly the same error and nothing is loaded.
[xeokit plugin TreeViewPlugin]: Failed to build storeys hierarchy for model 'design' - perhaps this model is not an IFC model?

I'm on a Windows 10 machine. 
The strange thing is that the xkt file is displayed OK when I use the xeokit-sdk to build a viewer.

Does anyone have any idea to help me solve this ?

Thank you !

**Comment by jerto** [comment]
Problem solved. We have to use the latest xeokit-gltf-to-xkt
So basically, what you have to do is :
npm uninstall xeokit-gltf-to-xkt
npm install --force @xeokit/xeokit-gltf-to-xkt@0.0.3 -g
