### ISSUE TITLE
Can the viewer be deployed on MS-IIS?

### ISSUE THREAD

**Issue by gisfinder** [xeokit/xeokit-bim-viewer#47]
I tested it on IIS but failed. The "geometry.xkt" is not identified by IIS. The error info is :
HTTP Error 404.3 - Not Found
The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map.

**Comment by xeolabs** [comment]
Yes it should work fine on MS IIS, since it's all standard portable  HTML/JavaScript.

Perhaps your file server needs a MIME type configuration for the ".xkt" extension?

**Comment by gisfinder** [comment]
After Mime Type configured on IIS the model can be loaded.
