### ISSUE TITLE
Applying BCF with section planes does not update the section planes counter in the toolbar

### ISSUE THREAD

**Issue by wielinde** [xeokit/xeokit-bim-viewer#56]
Steps to reproduce:

- Create a BCF viewpoint containing a section plane.
- Reset the view
- Apply that BCF viewpoint

Expected behavior:
Section planes counter is 1

Current behavior:
Section planes counter is 0

**Comment by xeolabs** [comment]
Fixed by https://github.com/xeokit/xeokit-bim-viewer/commit/62286ce889c94673c5a713abe44c88e1732466e1
