### ISSUE TITLE
How to prepare a point cloud for xeokit?

### ISSUE THREAD

**Issue by cemunds** [xeokit/xeokit-bim-viewer#58]
The metadata says that the MAPPointCloud example in this repository was created with the xeokit-gltf-to-xkt tool. However, how was the point cloud converted to gltf in the first place? I have point clouds in typical formats like .ply, .e57 or .laz. I could not find a tool to go from any of these formats to gltf directly. I also tried converting the point cloud to .obj first using Blender, followed by obj2gltf, but it results in an error saying the .obj file has no geometry. I assume that since the file only contains vertices and not a complete mesh, obj2gltf cannot work with that.

**Comment by xeolabs** [comment]
The glTF point was contributed by a user, who unfortunately cannot share any details on how they created it. We only use it to demonstrate point cloud viewing capabilities.

To convert an LAZ/LAS to XKT, for loading into ````xeokit-bim-viewer````, please see: https://www.notion.so/xeokit/Viewing-an-LAZ-Point-Cloud-c45cdaae64514170be91c37d6827c9ca
