### ISSUE TITLE
Remove delay in the rendering of edges

### ISSUE THREAD

**Issue by jerto** [xeokit/xeokit-bim-viewer#71]
Hi,

The bim viewer is awesome but I noticed a difference with the SDK. 
When I run this demo ( https://xeokit.github.io/xeokit-sdk/examples/#postEffects_SAO_Schependomlaan ) edges always appear even if I drag or move the model.

When I run this one (https://xeokit.github.io/xeokit-bim-viewer/app/index.html?projectId=Schependomlaan&tab=storeys), there is a delay before the rendering of edges.

Can this delay be removed ?

Thanks in advance for your answer.

**Comment by jerto** [comment]
I answer my own question. 
By unminifying xeokit-bim-viewer.es.js I managed to change the delay.
Line 11281 : let i=0
Line 11295 : //(this._startFade(),
Line 11297 : }, 0),

This removes nearly all the delay and fade effect. As a drawback, the animation is less smooth but the rendering of edges is way quicker. As my main concern is efficiency , it suits me well.

Feel free to comment this method and point me on a proper way to achieve this goal.

**Comment by xeolabs** [comment]
Hi, that delay is hardwired into the BIMViewer by design, so not a defect - it works by switching to cheaper rendering (without edges and SAO) while interacting with the scene, then switching to quality rendering (edges and SAO) after a short delay with no interaction.

**Comment by jerto** [comment]
Thanks for the answer. 
I understand the choice to hardcode this in the viewer. 
So i'll just stick to my quick and dirty hack as it fits my needs.
