### ISSUE TITLE
Unsupported .XKT file version: 9

### ISSUE THREAD

**Issue by OsamaShabrez** [xeokit/xeokit-bim-viewer#81]
`[xeokit plugin XKTLoader]: Unsupported .XKT file version: 9 - this XKTLoaderPlugin supports versions 1,2,3,4,5,6,7,8`

I converted a very simple IFC using ~~CLI tools~~ xeokit-xkt-utils and placed it inside projects. When I try to access this file, XKT loader plugin complains, it is not supported. I took the latest `dist` folder contents but the issue still persists.

Code to generate XKT file from IFC:

```
const convert2xkt = require("@xeokit/xeokit-xkt-utils/dist/convert2xkt.cjs.js");

const sourceFile = process.argv[2];
const targetFile = sourceFile + ".xkt";

console.log("IFC source: " + sourceFile);
console.log("XKT target: " + targetFile);

convert2xkt({
    source: sourceFile,
    output: targetFile
}).then(() => {
    console.log("Converted.");
}, (errMsg) => {
    console.error("Error: conversion failed, " + errMsg)
});
```

usage: `node index.js C:\temp\drawing.ifc`

I am guessing I need the latest XKT loader plugin but where can I find it? Thanks for your help.

**Comment by xeolabs** [comment]
I can't seem to reproduce this issue. These are the steps I followed:

- made a fresh clone of ````xeokit-bim-viewer```` 2.3.11
- converted a test IFC to XKT v9 using the latest ````xeokit-xkt-utils````
- replaced ````/app/data/projects/RevitSamples/models/rac_advanced_sample_project/geometry.xkt```` with the XKT file
- loaded that project in ````xeokit-bim-viewer````

See screenshot - JS console logs that it's successfully loaded XKT v9 - seems to be OK.

![Screenshot from 2021-11-10 10-09-05](https://user-images.githubusercontent.com/83100/141089211-e3cb92b8-331e-42c6-838a-e5d31e4b8769.png)

**Comment by xeolabs** [comment]
Can't reproduce with public ````xeokit-bim-viewer```` demo - note the JS console message indicating successful loading of XKT v9 file.  

![Screenshot from 2021-11-10 10-47-23](https://user-images.githubusercontent.com/83100/141090086-9258256b-fc8e-4d4f-8bb5-e04f0502ac42.png)
