### ISSUE TITLE
Help wanted running locally within Visual Studio 

### ISSUE THREAD

**Issue by alex4omnicon** [xeokit/xeokit-bim-viewer#99]
Hello,

could someone explain, how to run the viewer locally with visual studio code?

thanks and best regards
Alex

**Comment by nicolalopatriello** [comment]
Use it with a webserver. For example install `http-server` and next serve it.

`http-server xeokit-bim-viewer/` 

App will be serverd to first available port (for example `localhost:8080`)

Next run a project, for example:

`http://localhost:8080/app/?projectId=WestRiversideHospital`
